In [1]:
import pandas as pd

df = pd.read_csv("../data/criteo_ctr_drop_dataset.csv")

df['date'] = pd.to_datetime(df['date'])
df['ctr'] = df['clicks']/df['impressions']

In [14]:
before = df[df['date'] < '2026-06-15']

In [15]:
after = df[df['date'] >= '2026-06-15']

In [16]:
device_before = (
    before.groupby('device')
    .agg({'clicks':'sum',
          'impressions':'sum'})
)

device_before['ctr_before'] = (
    device_before['clicks']
    /
    device_before['impressions']
)

device_before

         clicks  impressions  ctr_before
device
Desktop    8706       175407    0.049633
Mobile    20104       401096    0.050123

In [17]:
device_after = (
    after.groupby('device')
    .agg({'clicks':'sum',
          'impressions':'sum'})
)

device_after['ctr_after'] = (
    device_after['clicks']
    /
    device_after['impressions']
)

device_after

         clicks  impressions  ctr_after
device
Desktop    9977       201825   0.049434
Mobile    21030       470393   0.044707

In [18]:
device_analysis = pd.concat(
    [
        device_before['ctr_before'],
        device_after['ctr_after']
    ],
    axis=1
)

device_analysis

         ctr_before  ctr_after
device
Desktop    0.049633   0.049434
Mobile     0.050123   0.044707

In [19]:
mobile_before = before[
    before['device']=='Mobile'
]

mobile_after = after[
    after['device']=='Mobile'
]
mobile_after

,date,user_id,country,device,browser,campaign,impressions,clicks,page_load_time,purchases,revenue,ctr
1,2026-06-20,2,USA,Mobile,Chrome,Sports,10,1,1.323906,0,0.0,0.100000
6,2026-06-29,7,UK,Mobile,Chrome,Sports,14,0,1.095381,0,0.0,0.000000
7,2026-06-21,8,UK,Mobile,Safari,Travel,6,0,4.447061,0,0.0,0.000000
11,2026-06-23,12,USA,Mobile,Safari,Travel,10,0,4.046896,0,0.0,0.000000
14,2026-06-24,15,France,Mobile,Firefox,Fashion,14,1,0.782715,0,0.0,0.071429
...,...,...,...,...,...,...,...,...,...,...,...,...
99988,2026-06-20,99989,USA,Mobile,Chrome,Sports,20,0,0.995900,0,0.0,0.000000
99991,2026-06-22,99992,Germany,Mobile,Chrome,Electronics,16,1,1.135716,0,0.0,0.062500
99994,2026-06-23,99995,UK,Mobile,Safari,Travel,9,0,4.014095,0,0.0,0.000000
99997,2026-06-21,99998,Germany,Mobile,Firefox,Electronics,5,0,1.405824,0,0.0,0.000000
99998,2026-06-29,99999,Germany,Mobile,Chrome,Travel,16,0,0.964657,0,0.0,0.000000

In [20]:
browser_before=( mobile_before.groupby('browser').agg({'clicks':'sum','impressions':'sum'}))

In [21]:
browser_before

         clicks  impressions
browser
Chrome    10089       201017
Firefox    4049        80275
Safari     5966       119804

In [22]:
browser_before['ctr_before']=browser_before['clicks']/browser_before['impressions']

In [23]:
browser_before

         clicks  impressions  ctr_before
browser
Chrome    10089       201017    0.050190
Firefox    4049        80275    0.050439
Safari     5966       119804    0.049798

In [26]:
browser_after=(mobile_after.groupby('browser').agg({'clicks':'sum','impressions':'sum'}))
browser_after['ctr_after']=browser_after['clicks']/browser_before['impressions']

In [27]:
browser_after

         clicks  impressions  ctr_after
browser
Chrome    11776       234544   0.058582
Firefox    4808        93866   0.059894
Safari     4446       141983   0.037111

In [28]:
browser_analysis = pd.concat(
    [
        browser_before['ctr_before'],
        browser_after['ctr_after']
    ],
    axis=1
)

browser_analysis

         ctr_before  ctr_after
browser
Chrome     0.050190   0.058582
Firefox    0.050439   0.059894
Safari     0.049798   0.037111

Now we understood that the click through rate was decreased due to some issue in safari

In [29]:
mobile_safari = df[
    (df['device']=='Mobile')
    &
    (df['browser']=='Safari')
]

In [34]:
mobile_safari.groupby(
    mobile_safari['date']<'2026-06-15'
)['page_load_time'].mean()

date
False    3.820362
True     1.198113
Name: page_load_time, dtype: float64